gopacket/gopacket

layers/lldp.go
Trailing whitespace in two LLDP strings has been removed. I searched across the `layers` package and didn't see any other strings like this.
=> Clean up LLDP subtype and class strings

.gitignore, layers/ip4.go, packet.go, pcapgo/capture.go, pcapgo/capture_test.go
I originally prepared this PR for the google/gopacket repo.
Although it's already quite a while I finally managed to re-create it to (hopefully) merge it now :smile:
It's mostly about adding support for `  context.Context`   but I also optimized some small things to avoid allocations in hot paths:
- re-order the IPv4 header parsing
- `  NewZeroCopyPacketSource`  
I'm using these changes already for quite some time so I'm 'optimistic' they're working as expected :smile:
=> feat(pcapgo): support cancellation with context.Context

pcapgo/capture.go
We recently switched to this version of `gopacket` and started seeing the following errors when building for `linux-386` targets:
```
Error: /home/runner/go/pkg/mod/github.com/gopacket/gopacket@v1.1.0/pcapgo/capture.go:112:29: cannot use tstamp.Sec (variable of type int32) as int64 value in argument to time.Unix
Error: /home/runner/go/pkg/mod/github.com/gopacket/gopacket@v1.1.0/pcapgo/capture.go:112:41: cannot use tstamp.Nsec (variable of type int32) as int64 value in argument to time.Unix
Error: /home/runner/go/pkg/mod/github.com/gopacket/gopacket@v1.1.0/pcapgo/capture.go:115:29: cannot use tstamp.Sec (variable of type int32) as int64 value in argument to time.Unix
```
This PR fixes the issue by explicitly casting these values to `int64` before use in the `time.Unix` call.
=> Fix integer size for linux-386 builds

afpacket/afpacket.go
Do a setsockopt with SO_DETACH_FILTER when TPacket.SetBPF() is called with a empty BPF instruction list.
=> Support removing BPF filter from AF_PACKET socket

layers/pflog.go
OpenBSD pflog adds some fields which aren't present in FreeBSD, as a result the packet's padding is different.
This change was made a long time ago in https://github.com/openbsd/src/commit/72d1fa51d6773e9a0559c1094601272f195c2633
I've brought over the change from https://github.com/google/gopacket/pull/1066, thanks @dennisoelkers for that. This doesn't add parsing for the additional fields (although this commit is enough to unblock the error, you can get the additional fields out of `.Contents` manually, but it might make sense to add them to the layer)
=> Relax length check on pflog packets

layers/dhcp_test.go, layers/dhcpv4.go
The DHCPv4 header field "HardwareOpts" is misleading. This fields original name by RFC 2131, which just takes it from RFC 951, is "hops". It has never changed meaning and still reflects number of relay agents it passed, as described in RFC 951 section 8.
This commit changes the name of the field "HardwareOpts" to "RelayHops".
=> Fix DHCPv4 header field name hops

base.go, checksum.go, checksum_test.go, layers/gre.go, layers/icmp4.go, layers/icmp6.go, layers/ip4.go, layers/ip4_test.go, layers/tcp.go, layers/tcpip.go, layers/udp.go, layers/udp_test.go, packet.go
Thank you for forking `google/gopacket` and keeping it alive!
Originally submitted here: https://github.com/google/gopacket/pull/1057
With a commit from: https://github.com/google/gopacket/pull/883
---
This PR adds a LayerWithChecksum interface for layers that have a checksum with a function to verify it and implements this function for all layers that use the internet checksum from RFC1071 and where the checksum computation was implemented (for SerializeTo).
It also adds a way to verify the checksums of all layers of a packet and retrieve a list of all found mismatches.
To implement this, I refactored the internet checksum calculation code, deduplicated it and made it a little bit more modular. There are now two functions: ComputeChecksum and FoldChecksum.
These split-up functions make …
=> Verify checksums

layers/gen.go, layers/iana_ports.go, layers/ports.go
Initializing huge maps as global variables causes a lot of allocations while importing the package (even if the respective feature is never used).
Rewrite to use `switch` statements and regen `iana_ports.go`.
As observed with `GODEBUG=inittrace=1`:
before:
```
init github.com/gopacket/gopacket/layers @0.52 ms, 1.7 ms clock, 395496 bytes, 120 allocs
```
after:
```
init github.com/gopacket/gopacket/layers @1.0 ms, 1.4 ms clock, 27760 bytes, 86 allocs
```
Time can be ignored, but reduction in memory allocation is visible.
=> refactor: optimize port map to switch statement

ip4defrag/defrag.go, ip4defrag/defrag_test.go
This PR will fix a bug where the defragmenter fails on pcap files that has a final fragment that is smaller than 8 octets.
The final fragment should be allowed to be less than 8 octets according to the standard.
For reference:
https://packetpushers.net/ip-fragmentation-in-detail/
https://stackoverflow.com/a/7846487/1642369
=> fix(ip4defrag): allow final fragment to be less than 8 octets

layers/enums_generated.go, layers/gen2.go
Some metadata arrays are pretty big (e.g. `EthernetTypeMetadata` has 65536 slots), while only a small subset of the values are filled with actual decoders (e.g. for `EthernetTypeMetadata` that is 18 entries).
The rest were filled in `func init()` to return error on access. This leads to noticeable startup time delay, as these mappings are pretty big.
This change simply leaves not used slots unset (zero value), and the request error values are generated on access to the slot.
Comparing time with `GODEBUG=inittrace=1` on a simple test program which imports `gopacket/layers`:
before:
```
init internal/bytealg @0 ms, 0 ms clock, 0 bytes, 0 allocs
init runtime @0.009 ms, 0.063 ms clock, 0 bytes, 0 allocs
init math @0.18 ms, 0 ms clock, 0 bytes, 0 allocs
init errors @0.19 ms, 0 ms clock, 0 …
```
=> refactor: don't fill empty metadata slots

reassembly/memory.go
Allow `New` to return nil to prevent stream creation. 
Useful in case when the stream is reopened because of last ACK.
This addresses this issue: https://github.com/google/gopacket/issues/427
=> allow tcp stream creation prevention

layers/ip6.go
This PR adds the `SerializeTo` function to `IPv6Fragment`, to allow the fragment to be serialized and used when creating fragmented IPv6 packets (when using `gopacket.SerializeLayers()`)
=> Add SerializeTo to IPv6Fragment

layers/radiotap.go, layers/radiotap_test.go
On rare occasions, it is possible that the length field in the RadioTap layer is bigger than the actual data length which results in a panic when trying to reference the payload. If it's bigger, simply truncate the RadioTap length to the length of the actual data to allow processing of what we can safely.
=> Fix RadioTap decoding panic

layers/dot11.go, layers/dot11_test.go
Similar to https://github.com/secdev/scapy/pull/1175, only RA (addr1) is being parsed at the moment, update to include the processing of TA (addr2).
=> Fix BlockAck missing TA

pcap/pcap_unix.go
Otherwise it results
```
src/github.com/gopacket/gopacket/pcap/pcap_unix.go:345:18: cannot use _Ctype_gopacket_time_secs_t(ci.Timestamp.Unix()) (value of type _Ctype_long) as _Ctype_longlong value in assignment
src/github.com/gopacket/gopacket/pcap/pcap_unix.go:346:19: cannot use _Ctype_gopacket_time_usecs_t(ci.Timestamp.Nanosecond() / 1000) (value of type _Ctype_long) as _Ctype_longlong value in assignment
```
=> Fix time type when build with _TIME_BITS=64 on 32bit arch

pcapgo/ngread.go
This function initializes a new reader, not a writer.
=> Fixed typo in the documentation for NewNgReader

layers/dns.go
We are using gopacket to parse messages in Inpektor Gadget using [trace dns gadget](https://www.inspektor-gadget.io/docs/v0.28.0/builtin-gadgets/trace/dns/). Users have an option to filter messages using `--filter rcode:"No Error"` so an extra space in a message can be an issue for the users! 
ref: https://github.com/google/gopacket/pull/1169
=> layers: Remove trailing whitespace for Server Failure string

pcap/pcap_unix.go
When cross compiling on `amd64-linux` by `CGO_ENABLED=1 GOOS=linux GOARCH=mips CC=mips-linux-gnu-gcc CGO_LDFLAGS="-L/tmp/libpcap-$PCAPV" go build`, this error would occur:
```
../../../go/pkg/mod/github.com/gopacket/gopacket@v1.3.0/pcap/pcap_unix.go:355:18: cannot use _Ctype_gopacket_time_secs_t(ci.Timestamp.Unix()) (value of type _Ctype_gopacket_time_secs_t) as _Ctype___time64_t value in assignment
../../../go/pkg/mod/github.com/gopacket/gopacket@v1.3.0/pcap/pcap_unix.go:356:19: cannot use _Ctype_gopacket_time_usecs_t(ci.Timestamp.Nanosecond() / 1000) (value of type _Ctype_gopacket_time_usecs_t) as _Ctype___suseconds64_t value in assignment
```
After some investigation, the reason is that the C macro at the beginning of `pcap/pcap_unix.go` failed to define `gopacket_time_secs_t` and …
=> Fix mips cross compile

layers/dns.go, layers/dns_test.go
This pull request introduces support for RRSIG and DNSKEY record types in the DNS layer. The changes include the addition of these record types to the DNSType enumeration, as well as the implementation of their respective structures, encoding methods, and size calculations. This enhancement allows for better handling of DNSSEC-related records, improving the overall functionality of the DNS module.
=> Add RRSIG and DNSKEY record types to DNS layer

layers/ospf.go, layers/ospf_test.go
This is a bugfix.
Since the origin upstream maintained by google is stall for a long time, I just submit the fix here.
There might be more contributes to OSPFv2 because I am currently working on it.
According to [RFC 2328 A.4.1](https://datatracker.ietf.org/doc/html/rfc2328#autoid-28)
The `LSType` field should be located at 4th byte of LSAheader.
and the missing LSOptions field should be at 3th.
=> OSPFv2: fix DbDesc LSAheader parse

layers/dot11.go, layers/dot11_test.go
Move offset check within check for vendor extension (221) as this appears to be a bug as the else statement never uses . Previously this would cause small elements to fail processing as it wasn't limited to only vendor elements.
Small Dot11InformationElements that were failing included:
```
Tag: Power Constraint: 0
Tag Number: Power Constraint (32)
Tag length: 1
Local Power Constraint: 0
// 0x20, 0x01, 0x00
```
and 
```
Tag: ERP Information
Tag Number: ERP Information (47)
Tag length: 1
ERP Information: 0x00
// 0x2f, 0x01, 0x00
```
The `len(data) < offset+4` is a valid check, but _only_ for a vendor specific element such as:
```
Tag: Vendor Specific: Broadcom
Tag Number: Vendor Specific (221)
Tag length: 9
OUI: 00:10:18 (Broadcom)
Vendor Specific OUI Type: 2
Vendor Specific Data: …
```
=> Fix Dot11InformationElement processing

layers/.lint_blacklist, layers/multipathtcp.go, layers/tcp.go, layers/tcp_test.go
- Support for decoding MPTCPv0 (RFC6824) and MPTCPv1 (RFC8684) packets
- Test for MPTCP
This replaces #63.
Work from @nkeukeleire, originally published on https://github.com/google/gopacket/pull/870.
On top of that, I did a rebase, fixed the conflicts, a few typos, ran the tests, nothing major.
=> Add MPTCP Options in the TCP Layer Decoder

layers/decode_test.go, layers/sctp.go
Hello there,
I came across a problem while working with SCTP packets. According to the specification of SCTP there a packet might contain multiple chunks bundled together if the packet size allows it.
> [1.5.5. ](https://datatracker.ietf.org/doc/html/rfc9260#section-1.5.5)[Chunk Bundling](https://datatracker.ietf.org/doc/html/rfc9260#name-chunk-bundling)
>
>As described in [Section 3](https://datatracker.ietf.org/doc/html/rfc9260#sec_sctp_packet_format), the SCTP packet as delivered to the lower layer consists of a common header followed by one or more chunks. Each chunk contains either user data or SCTP control information. An SCTP implementation supporting bundling on the sender side might delay the sending of user messages to allow the corresponding DATA chunks to be bundled.
Sadly, …
=> Add support for bundled SCTP chunks

afpacket/afpacket.go, afpacket/sockopt_linux.go, htons/htons.go, htons/htons_test.go, pcapgo/capture.go
Currently afpacket/pcapgo fails to receive any packet in big endian hosts because the interface index is never matched due the swap, regardless the host endianess
An alternative for unsafe would be add a dependency to Go maintained [x/sys/cpu](https://pkg.go.dev/golang.org/x/sys/cpu#IsBigEndian) and hope the tag list is maintained accordingly as architectures are added and removed, I found it too big of a dependency for a simple question, and that's cheap to compute at runtime, but it's up to you.
=> afpacket/pcapgo: fix htons in big endian systems

pcap/pcap_unix.go
Currently this checks whether a type is defined which does not appear to work. Instead, we check for the specific cases where time64 would be used instead of time.
Closes #89
=> Change ifdef for 64-bit time to check for the right thing

pcapgo/capture.go
This allows pcapgo to cooperate with the Go runtime poller to not block entire OS thread on operations.
This is rebase of https://github.com/google/gopacket/pull/911
=> Make pcapgo EthernetHandle use runtime poller

layers/dns.go
avoid panic in case of a root zone SignerName
resolve https://github.com/gopacket/gopacket/issues/100
=> avoid panic in case of a root zone SignerName

layers/geneve.go, layers/geneve_test.go
Before this patch, the Geneve layer would not fully implement `DecodingLayer`. This would prevent Geneve to be added as a `DecodingLayer` to `gopacket.NewDecodingLayerParser()`:
cannot use &Geneve{} (value of type *Geneve) as gopacket.DecodingLayer value in argument to gopacket.NewDecodingLayerParser: *Geneve does not implement gopacket.DecodingLayer (missing method CanDecode)
This patch implements `(*Geneve).CanDecode()` and a test to ensure Geneve can be used as a `DecodingLayer`.
=> geneve: implement DecodingLayer

layers/gtp.go
GTPv1U has different message types. Data (255) carries nested IPv4, IPv6 or PPP packet.  Other messages such as Echo Request / Response don't.
Check the message type first and only parse payload as IPv4 / IPv6 / PPP in data PDUs.
=> gtpv1u: check message type when decoding payload

.github/workflows/push_pr.yaml
Potential fix for [https://github.com/gopacket/gopacket/security/code-scanning/5](https://github.com/gopacket/gopacket/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly set the permissions for the `GITHUB_TOKEN` to `contents: read`, which is sufficient for the operations performed in this workflow. This change ensures that the workflow adheres to the principle of least privilege and avoids granting unnecessary permissions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 5: Workflow does not contain permissions

layers/ipsec.go, layers/ipsec_test.go
Before this patch, the IPSecAH and IPSecESP layer would not fully implement DecodingLayer. This would prevent them to be added as a DecodingLayer to gopacket.NewDecodingLayerParser():
cannot use &IPSecAH{} (value of type *IPSecAH) as gopacket.DecodingLayer value in argument to gopacket.NewDecodingLayerParser: *IPSecAH does not implement gopacket.DecodingLayer (missing method CanDecode)
This patch implements (*IPSecAH).CanDecode() and (*IPSecESP).CanDecode() and a test to ensure they can be used as a DecodingLayer.
=> ipsec: implement DecodingLayer

layers/dot11.go, layers/dot11_test.go
Possible for the offset+4 to be greater than offset+m.Length resulting in a slice panic. Protect 221 and 255 which a check to ensure the start of the slice isn't greater.
Associated test will cause the panic on un-patched code with out of bounds slice.
=> Fix Dot11InformationElement parsing panic
